[package]
name = "umwelt-info"
authors = ["Adam Reichold <adam.reichold@uba.de>"]
repository = "https://github.com/adamreichold/umwelt-info"
license = "AGPL-3.0"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
askama = "0.11"
axum = "0.5"
bincode = "1.3"
cap-std = "0.25"
futures-util = "0.3"
quick-xml = { version = "0.23", features = ["serialize"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tantivy = "0.18"
tokio = { version = "1.0", features = ["full"] }
toml = "0.5"
tower-http = { version = "0.3", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.2", features = ["serde"] }
uuid = { version = "1.1", features = ["serde"] }

[profile.release]
lto = "thin"
