[[sources]]
name = "stadt-leipzig"
type = "ckan"
url = "https://opendata.leipzig.de/"
source_url = "https://opendata.leipzig.de/dataset/{{name}}"
concurrency = 3

[[sources]]
name = "govdata"
type = "ckan"
url = "https://www.govdata.de/ckan/"
source_url = "https://www.govdata.de/web/guest/suchen/-/details/{{name}}"
concurrency = 5
batch_size = 1000

#[[sources]]
#name = "geodatenkatalog"
#type = "csw" # GeoNetwork
#url = "http://gdk.gdi-de.org/gdi-de/srv/ger/csw"
#source_url = "http://gdk.gdi-de.org/gdi-de/srv/ger/catalog.search#/metadata/{{id}}"
#concurrency = 5

[[sources]]
name = "uba-gdi"
type = "csw" # SmartFinder
url = "https://gis.uba.de/smartfinder-csw/api/"
source_url = "https://gis.uba.de/smartfinder-client/?lang=de#/datasets/iso/{{id}}"

[[sources]]
name = "wasser-de"
type = "wasser_de"
url = "https://www.wasser-de.de/"
